# Generated by Django 5.2.6 on 2026-10-08 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_metadata_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sex_at_birth',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('intersex', 'Intersex')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('sex_at_birth__isnull', True), ('sex_at_birth__in', ['female', 'male', 'intersex']), _connector='OR'), name='participant_sex_at_birth_valid'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('birth_year__isnull', True), ('birth_year__gte', 1900), _connector='OR'), name='participant_birth_year_valid'),
        ),
    ]
