# Generated by Django 5.2.6 on 2026-10-09 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_sex_birth_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='participant_sex_at_birth_valid',
        ),
        migrations.AlterField(
            model_name='participant',
            name='sex_at_birth',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('intersex', 'Intersex'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('sex_at_birth__isnull', True), ('sex_at_birth__in', ['female', 'male', 'intersex', 'other']), _connector='OR'), name='participant_sex_at_birth_valid'),
        ),
    ]
