# Generated by Django 5.2.6 on 2026-10-06 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_seed_roles_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search', 'Search'), ('verify_rut', 'Verify RUT')], max_length=16)),
                ('query', models.CharField(blank=True, max_length=96)),
                ('outcome', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_access_logs', to='accounts.appuser')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reception_access_log',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='reception_log_target_idx')],
            },
        ),
    ]
