# Generated by Django 5.2.6 on 2026-09-07 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacogeneticSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Sistema')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sistema Farmacogenético',
                'verbose_name_plural': 'Sistemas Farmacogenéticos',
            },
        ),
        migrations.CreateModel(
            name='RsidExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_id', models.CharField(max_length=20, verbose_name='rsID')),
                ('genotype', models.CharField(max_length=10, verbose_name='Genotype')),
                ('phenotype_name', models.TextField(verbose_name='Phenotype name')),
                ('freq_chile_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chile frequency percent')),
                ('phenotype_description', models.TextField(verbose_name='Phenotype description')),
            ],
            options={
                'verbose_name': 'RSID extra info',
                'verbose_name_plural': 'RSID extra info',
                'db_table': 'rsid_extra_info',
                'indexes': [models.Index(fields=['rs_id'], name='rsid_extra_rsid_idx'), models.Index(fields=['phenotype_name'], name='rsid_extra_pheno_idx')],
                'unique_together': {('rs_id', 'genotype', 'phenotype_name')},
            },
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=20, verbose_name='rsID')),
                ('genotipo', models.CharField(max_length=10, verbose_name='Genotipo')),
                ('fenotipo', models.TextField(verbose_name='Fenotipo')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('grupo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo del Rasgo')),
                ('cromosoma', models.CharField(blank=True, max_length=5, null=True, verbose_name='Cromosoma')),
                ('posicion', models.BigIntegerField(blank=True, null=True, verbose_name='Posición genómica')),
                ('alelo_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alelo de referencia')),
                ('alelo_alternativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alelo alternativo')),
                ('nivel_riesgo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de riesgo')),
                ('magnitud_efecto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Magnitud del efecto')),
                ('fuente_base_datos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente de base de datos')),
                ('tipo_evidencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de evidencia')),
                ('fecha_actualizacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de actualización')),
                ('continente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Continente')),
                ('af_continente', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Frecuencia Alélica - Continente')),
                ('fuente_continente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente - Continente')),
                ('poblacion_continente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Población - Continente')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('af_pais', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Frecuencia Alélica - País')),
                ('fuente_pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente - País')),
                ('poblacion_pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Población - País')),
                ('pharmacogenetic_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snps', to='genetics.pharmacogeneticsystem', verbose_name='Sistema Farmacogenetico')),
            ],
            options={
                'verbose_name': 'SNP',
                'verbose_name_plural': 'SNPs',
                'db_table': 'snps',
            },
        ),
        migrations.CreateModel(
            name='UserSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_associations', to='genetics.snp', verbose_name='SNP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_snps', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SNP de Usuario',
                'verbose_name_plural': 'SNPs de Usuarios',
                'db_table': 'user_snps',
            },
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['rsid'], name='snps_rsid_789da6_idx'),
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['categoria'], name='snps_categor_03f777_idx'),
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['cromosoma'], name='snps_cromoso_b4fdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['nivel_riesgo'], name='snps_nivel_r_816f9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('rsid', 'genotipo', 'fenotipo', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='usersnp',
            index=models.Index(fields=['user'], name='user_snps_user_id_4cc690_idx'),
        ),
        migrations.AddIndex(
            model_name='usersnp',
            index=models.Index(fields=['snp'], name='user_snps_snp_id_4178b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersnp',
            unique_together={('user', 'snp')},
        ),
    ]
