# Generated by Django 5.2.6

import django.db.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationEmailChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Desafío de correo de registro",
                "verbose_name_plural": "Desafíos de correo de registro",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"],
                        name="accounts_reg_email_created_idx",
                    ),
                    models.Index(
                        fields=["expires_at"],
                        name="accounts_reg_expiry_idx",
                    ),
                ],
            },
        ),
    ]
