# Generated by Django 5.2.6 on 2026-09-29 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration_email_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('CLIENTE', 'Client'), ('ADMIN', 'Administrator'), ('ANALISTA', 'Analyst'), ('RECEPCION', 'Reception')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['CLIENTE', 'ADMIN', 'ANALISTA', 'RECEPCION'])), name='role_functional_code_valid')],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oidc_issuer', models.TextField(blank=True, null=True)),
                ('oidc_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_users', to='accounts.role')),
            ],
            options={
                'db_table': 'app_user',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('oidc_issuer__isnull', True), ('oidc_subject__isnull', True)), models.Q(('oidc_issuer__isnull', False), ('oidc_subject__isnull', False), models.Q(('oidc_issuer', ''), _negated=True), models.Q(('oidc_subject', ''), _negated=True)), _connector='OR'), name='app_user_oidc_pair_complete'), models.UniqueConstraint(fields=('oidc_issuer', 'oidc_subject'), name='app_user_oidc_identity_unique')],
            },
        ),
    ]
