# Generated by Django 5.2.6 on 2026-10-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_roles_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationEmailChallenge',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
