# Generated by Django 5.2.6 on 2026-09-07 19:13

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('rut', models.CharField(help_text='RUT en formato XXXXXXX-R (ejemplo: 12345678-9 o 1234567-K)', max_length=12, null=True, unique=True, validators=[profiles.models.validate_rut_format], verbose_name='RUT')),
                ('service_status', models.CharField(choices=[('NO_PURCHASED', 'Sin servicio'), ('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], db_index=True, default='NO_PURCHASED', max_length=20)),
                ('service_updated_at', models.DateTimeField(auto_now=True)),
                ('sample_code', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Código de Muestra')),
                ('sample_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación del código')),
                ('sample_status', models.CharField(choices=[('PENDING_COLLECTION', 'Pendiente de toma'), ('COLLECTED_PENDING_ANALYSIS', 'Muestra tomada / Pendiente de análisis'), ('SENT_TO_LAB', 'Enviada al laboratorio'), ('RECEIVED_AT_LAB', 'Recibida en laboratorio')], db_index=True, default='PENDING_COLLECTION', max_length=40, verbose_name='Estado de la muestra')),
                ('arrival_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Llegada confirmada en recepción')),
                ('sample_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de toma de muestra')),
                ('sample_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío al laboratorio')),
                ('report_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('report_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
