# Generated by Django 5.2.6

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="RUT en formato XXXXXXX-R (ejemplo: 12345678-9 o 1234567-K)",
                max_length=12,
                null=True,
                unique=True,
                validators=[profiles.models.validate_rut_format],
                verbose_name="RUT",
            ),
        ),
    ]
