# Generated by Django 5.2.6 on 2026-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_rut_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='arrival_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='report_filename',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='report_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sample_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sample_code_created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sample_sent_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sample_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sample_taken_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_updated_at',
        ),
    ]
